{% set name = "colormap" %}
{% set version = "1.3.0" %}
{% set sha256 = "8df95ee498257aeabd3c8f42b55eac9a095fbfa05fbcbe5ac751fc95d71b00da" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - matplotlib-base
    - easydev

test:
  imports:
    colormap
  requires:
    - python {{ python_min }}

about:
  home: https://pypi.org/project/colormap/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Utilities to ease manipulation of matplotlib colormaps and color codecs (e.g., hex2rgb)'
  doc_url: http://colormap.readthedocs.io/en/latest
  dev_url: https://github.com/cokelaer/colormap

extra:
  recipe-maintainers:
    - cokelaer
