travis:
  secure:
    BINSTAR_TOKEN: JF/xSk1Fk4a6j8YCYBa305WDJ1dISnZm60Xj4zSFF/tdEDCpso6mA8hG1D+MJTwADMBJRTnAWw+/tGTBFf5yLjj+eJ+CVcHeagwp1nWQy1zhfIypYwuFw1Yt6TUvjj+jJrtu5pA9a73E4KBY3UCHpLA61XnC4OOqzYL+4YfTp2nLOj7sTD4TChw+yx2iJLAfWZrw1Lp0oEtL7X7KDUXKCuH9upR9x5u1gFDCeSTSvqdA64okxmEttObxzZfVzAF/AHbb6wFFzOBYE1spqvDXfGaBudm2l+fMrKO3KzaK/Ob/TZ3tmeAyiIzicIAR965/Dmg9v+VR4YgJMAndFE+k13WIYeif7ZiBdQ+uRQrBcplJzeiv+xgMlh71iPNipaDRJCfQD9JoORHwa50az5RNQgPV6VWNHehYxqaPeRvEh0hQbZhtodG2Jk0hktYGoz7WEVgK4inNhpMProEpNdeFVeUzW9KSK9Xsrf5rWhcPFV5iU5+xPvw/x4J7yNjXtmrscMGjpR/sazAMp0LQa72tQOuh1Porc4S6sFbD+vrvl1WUeGXO35jO5pcko8KS9nsYTXRCrPxdGaQi4bH94+ax7PPfbLLl4aOIvTrLNO1Dr9jcmId0Rm8H7TzgQ+VrVU+Uj1ibyJQbAJNJg17o/xcl/ssErFN9qsYLCra796kIEqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
