travis:
  secure:
    BINSTAR_TOKEN: qLfjyn74N0dfNJ7hseQ2hu+j6FXce6Qgm74QpYv64/D06ZhIwkuIiT8NPEjB5ABsSFOsG2XiK1dsDvsDofk5nsGU8CKMacCdKumvBDc1El2O/635vVWsca08MNzyDrSib81jyTocoPHzepKkIIigpU7zW0NgeyXgEUxYdoWkpOcLUyTSRiTEkolmfbCV3nTfIlq7+RkUsgau7ncgCV0AoYPPrWXvHGNW1cdlN+l3H+yYZfiedR95s+zrdipnFK9XOkjl/EN5lLqz1ZfcR/Ad5/LFTA3rYluoIfHf+eEJf54o3Lqy0py7rBA8wwRLNd0JdrRjXub/RgH+KfdROvXNtGr5uD4XmeM4eV82LKOcrP9YKjqJUKp7Ln7skHuyyKSXrif8LfIy01SMOqTM3Eu8MZxRH+n8Tj4a/KTp0SQQKObzBBMY21YcAMG1mZib4P/aoHr/9sxgqGnwuMGoxCn3dbJ0cpUbMx8fzYbm+yDbdnXhiIYObuRbz7rT4Gbz98t5l6TsQgnZfwU3O34ETvh3I4+2WvDMya/d4pqHm5VcAXQbYFJs+zl7yvZHXnUfneSeCEXzJO3qL2Z9cexL5VgvwSjSINzfe5WLdZH9QOKM8Yph6+9nQyM4tNcuuD1VjYBawNIp/7VmfzKdvCJuBZa07V2GhlIcY+MRXBFLU4JeOC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
